document.addEventListener('DOMContentLoaded',()=>{
  initGlobalUI();
  if((location.pathname.split('/').pop()||'index.html')==='index.html') initHomepage();
  initMarketIntelligence();
  if(document.querySelector('#btc-price')) setInterval(initMarketIntelligence,60000);
  initTradingViewTabs();
});
function initGlobalUI(){
  const menu=document.querySelector('[data-menu]'),nav=document.querySelector('.nav');
  if(menu&&nav)menu.addEventListener('click',()=>nav.classList.toggle('open'));
  document.querySelectorAll('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const o=f.querySelector('.form-message');if(o){o.textContent='Thank you. This demo form is ready to connect to your CRM or email service.';o.hidden=false}f.reset()}));
  document.querySelectorAll('.brand .logo').forEach(l=>{l.textContent='';Object.assign(l.style,{backgroundImage:'url("logo.svg?v=20260903-1")',backgroundRepeat:'no-repeat',backgroundPosition:'center',backgroundSize:'contain',width:'178px',height:'62px',flex:'0 0 178px',border:'0',borderRadius:'0',boxShadow:'none',backgroundColor:'transparent'})});
  document.querySelectorAll('.brand').forEach(b=>{const s=b.querySelectorAll(':scope > span');if(s.length>1)s[1].style.display='none'});
  if(nav&&!nav.querySelector('a[href="market-intelligence.html"]')){const a=document.createElement('a');a.href='market-intelligence.html';a.textContent='Market Intelligence';const r=nav.querySelector('a[href="investor-relations.html"]');nav.insertBefore(a,r||nav.lastElementChild)}
  document.querySelectorAll('.lang,[data-lang],a.login,a[href="login.html"]').forEach(x=>x.remove());
}
function injectHomeDesign(){
  if(document.getElementById('terrahash-home-design'))return;
  const s=document.createElement('style');s.id='terrahash-home-design';s.textContent=`
  body{background:#f5f8f5;color:#102019}.site-header{height:88px;position:absolute;padding:0 3.2%;gap:28px;background:linear-gradient(180deg,rgba(2,11,10,.84),rgba(2,11,10,.15));backdrop-filter:blur(7px)}
  .brand{min-width:205px}.brand .logo{filter:drop-shadow(0 5px 16px rgba(0,0,0,.35))}.nav{gap:30px;font-size:13px}.nav a{padding:33px 0 27px}.header-actions{margin-left:4px}.hero{min-height:760px;padding:150px 7% 100px;background:#020b0a;display:block}.hero:before{background:linear-gradient(90deg,rgba(0,0,0,.82) 0%,rgba(0,0,0,.55) 35%,rgba(0,0,0,.05) 72%),linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.48))}.hero:after{height:35%;opacity:.35}.hero-copy{max-width:650px;padding-top:32px}.hero h1{font-size:clamp(44px,5vw,72px);max-width:680px}.hero-copy>p:not(.kicker){font-size:16px;line-height:1.75;max-width:590px}.buttons{margin-top:30px}.btn{padding:13px 27px;border-radius:9px}.hero-art{right:0;top:88px;width:62vw;height:672px;max-width:930px;z-index:1}.hero-stats{left:7%;right:7%;bottom:25px;border-radius:12px;padding:13px 22px;grid-template-columns:repeat(4,1fr);background:rgba(3,17,14,.76)}.trust-strip{margin:0 auto;max-width:1240px;border-radius:0 0 14px 14px}.section{max-width:1240px;padding:88px 0}.section-head{margin-bottom:30px}.section h2{font-size:40px}.feature-grid{gap:14px}.feature-card{min-height:245px;border-radius:14px}.dark-section{padding:0 7%;max-width:none}.dark-section>.section-head,.dark-section>.platform{max-width:1240px}.platform{gap:55px}.platform-visual{height:420px;border-radius:20px}.vision-grid{gap:60px}.cta{padding:90px 7%}.footer{padding-left:7%;padding-right:7%}
  .home-live-market{max-width:1240px!important;padding:82px 0 92px!important}.home-market-chart{margin-top:28px;background:#06110d;border:1px solid #214333;border-radius:18px;overflow:hidden;box-shadow:0 24px 70px rgba(2,26,15,.18)}.home-market-toolbar{display:flex;align-items:center;gap:12px;padding:12px 14px;border-bottom:1px solid #1b3529;background:#091a13}.home-market-tabs,.home-intervals{display:flex;gap:6px;overflow:auto}.home-market-tabs{flex:0 0 auto}.home-intervals{flex:0 0 auto;border-left:1px solid #294638;padding-left:12px}.home-market-tab,.home-interval{appearance:none;border:1px solid #315343;background:#10251c;color:#a9bbb2;border-radius:7px;padding:8px 12px;font:700 10px/1 inherit;cursor:pointer;white-space:nowrap}.home-market-tab.active,.home-interval.active{background:#77e43e;color:#07140c;border-color:#77e43e}.home-market-live{margin-left:auto;font-size:9px;letter-spacing:.11em;color:#8fa69a;font-weight:800;white-space:nowrap}.home-market-live i{display:inline-block;width:7px;height:7px;border-radius:50%;background:#55df72;box-shadow:0 0 0 4px rgba(85,223,114,.12);margin-right:7px}.home-market-title{display:flex;align-items:baseline;justify-content:space-between;gap:15px;padding:14px 18px 9px;color:#fff;background:#091811}.home-market-title strong{font-size:18px}.home-market-title span{font-size:10px;color:#82958b}.home-market-frame{height:620px;position:relative;background:#0b1411}.home-market-frame iframe{width:100%;height:100%;border:0;display:block}.home-chart-loading{position:absolute;inset:0;display:grid;place-items:center;color:#9eb1a8;font-size:12px;background:#0b1411;z-index:2}.home-chart-loading.hidden{display:none}.home-market-foot{display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap;padding:10px 16px 13px;color:#72867b;font-size:9px;letter-spacing:.03em;border-top:1px solid #193526;background:#091811}
  @media(max-width:1000px){.site-header{padding:0 20px}.nav{gap:16px}.hero{min-height:720px}.hero-art{opacity:.58;width:70vw}.hero-stats{left:4%;right:4%}.section{padding-left:6%;padding-right:6%}.home-live-market{padding-left:6%!important;padding-right:6%!important}.platform{grid-template-columns:1fr;gap:35px}}
  @media(max-width:760px){.site-header{height:70px}.brand .logo{width:150px!important;height:52px!important;flex-basis:150px!important}.nav{display:none}.nav.open{display:flex;position:absolute;top:70px;left:0;right:0;background:#06120e;flex-direction:column;align-items:flex-start;padding:15px 22px;gap:0}.nav.open a{padding:12px 0;width:100%}.menu{display:block;margin-left:auto}.hero{min-height:760px;padding:120px 6% 95px}.hero-copy{padding-top:10px}.hero-art{top:70px;width:100%;height:620px;opacity:.38}.hero-stats{display:none}.trust-strip{grid-template-columns:1fr 1fr;margin:0 6%}.trust-strip>div{padding:14px}.feature-grid,.news-grid,.cards-3{grid-template-columns:1fr 1fr}.section h2{font-size:33px}.home-market-toolbar{flex-wrap:wrap}.home-market-live{margin-left:0}.home-market-frame{height:500px}.home-market-title{flex-direction:column;align-items:flex-start}.footer-main{grid-template-columns:1fr 1fr}.footer-brand{grid-column:1/-1}}
  @media(max-width:520px){.trust-strip,.feature-grid,.news-grid,.cards-3,.footer-main{grid-template-columns:1fr}.hero h1{font-size:42px}.hero-copy>p:not(.kicker){font-size:14px}.buttons{flex-wrap:wrap}.section{padding-top:65px;padding-bottom:65px}.home-live-market{padding-top:60px!important;padding-bottom:65px!important}.home-market-frame{height:420px}.home-market-tab,.home-interval{padding:8px 10px}.home-market-title strong{font-size:16px}}
  `;document.head.appendChild(s);
}
function initHomepage(){
  injectHomeDesign();
  const heroArt=document.querySelector('.hero-art');
  if(heroArt){heroArt.innerHTML='';Object.assign(heroArt.style,{backgroundImage:'url("assets/homepage-hero.jpg?v=20260902-2")',backgroundSize:'cover',backgroundPosition:'center',backgroundRepeat:'no-repeat',borderRadius:'0',overflow:'hidden',boxShadow:'none',backgroundColor:'#061711',zIndex:'1'});}
  const platformImage=document.querySelector('.platform-photo img');
  if(platformImage){platformImage.src='image_H569_科技感机械臂元素背景_..._6.png';platformImage.alt='Integrated industrial automation and digital infrastructure';}
  initHomeMarketChart();
}
function chartUrl(symbol,interval='15'){return`https://www.tradingview.com/widgetembed/?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&hidesidetoolbar=0&symboledit=1&saveimage=0&theme=dark&style=1&timezone=Etc%2FUTC&withdateranges=1&hideideas=1&studies=Volume%40tv-basicstudies`}
function initHomeMarketChart(){
  const old=document.querySelector('.market-preview');if(!old)return;
  old.outerHTML=`<section class="section home-live-market"><div class="section-head"><div><p class="kicker">LIVE DIGITAL ASSET MARKET</p><h2>Real-time cryptocurrency<br>trading chart.</h2><p style="max-width:720px;color:#68766f;font-size:13px">Interactive market information for selected Binance spot pairs, with live candlesticks, volume, crosshair, zoom and multiple time ranges.</p></div></div><div class="home-market-chart"><div class="home-market-toolbar"><div class="home-market-tabs" role="tablist"><button type="button" class="home-market-tab active" data-home-tv="BINANCE:BTCUSDT" data-home-asset="Bitcoin / USD" aria-selected="true">BTC / USD</button><button type="button" class="home-market-tab" data-home-tv="BINANCE:ETHUSDT" data-home-asset="Ethereum / USD" aria-selected="false">ETH / USD</button><button type="button" class="home-market-tab" data-home-tv="BINANCE:SOLUSDT" data-home-asset="Solana / USD" aria-selected="false">SOL / USD</button></div><div class="home-intervals" role="tablist"><button type="button" class="home-interval active" data-home-interval="1">1m</button><button type="button" class="home-interval" data-home-interval="5">5m</button><button type="button" class="home-interval" data-home-interval="15">15m</button><button type="button" class="home-interval" data-home-interval="60">1H</button></div><span class="home-market-live"><i></i> LIVE · BINANCE SPOT</span></div><div class="home-market-title"><strong id="home-chart-title">Bitcoin / USD</strong><span id="home-chart-source">BINANCE:BTCUSDT · Live market chart</span></div><div class="home-market-frame"><div class="home-chart-loading" id="home-chart-loading">Connecting to live market chart…</div><iframe id="home-tv-chart" title="Live Binance cryptocurrency candlestick trading chart" loading="eager" allow="fullscreen" src="${chartUrl('BINANCE:BTCUSDT','1')}"></iframe></div><div class="home-market-foot"><span>LIVE DATA · CANDLESTICKS · VOLUME · CROSSHAIR · ZOOM · TIME RANGES</span><span>Market information only · Not investment advice</span></div></div></section>`;
  const frame=document.getElementById('home-tv-chart'),load=document.getElementById('home-chart-loading'),title=document.getElementById('home-chart-title'),source=document.getElementById('home-chart-source');
  const loadChart=(symbol,asset,interval)=>{if(load)load.classList.remove('hidden');if(title)title.textContent=asset;if(source)source.textContent=`${symbol} · Live market chart`;if(frame)frame.src=chartUrl(symbol,interval)};
  if(frame)frame.addEventListener('load',()=>load&&load.classList.add('hidden'));
  document.querySelectorAll('.home-market-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.home-market-tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');loadChart(b.dataset.homeTv,b.dataset.homeAsset,document.querySelector('.home-interval.active')?.dataset.homeInterval||'1')}));
  document.querySelectorAll('.home-interval').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.home-interval').forEach(x=>x.classList.remove('active'));b.classList.add('active');const a=document.querySelector('.home-market-tab.active');loadChart(a?.dataset.homeTv||'BINANCE:BTCUSDT',a?.dataset.homeAsset||'Bitcoin / USD',b.dataset.homeInterval)}));
}
const MARKET_ASSETS={bitcoin:{symbol:'BTC',coinpaprika:'btc-bitcoin',coinbase:'BTC-USD',binance:'BTCUSDT'},ethereum:{symbol:'ETH',name:'Ethereum',coinpaprika:'eth-ethereum',coinbase:'ETH-USD',binance:'ETHUSDT'},solana:{symbol:'SOL',name:'Solana',coinpaprika:'sol-solana',coinbase:'SOL-USD',binance:'SOLUSDT'}};
function n(v){v=Number(v);return Number.isFinite(v)?v:NaN}function text(id,v){const e=document.getElementById(id);if(e)e.textContent=v}function price(v){v=n(v);if(!Number.isFinite(v))return'—';if(v>=1000)return'$'+v.toLocaleString('en-US',{maximumFractionDigits:0});if(v>=1)return'$'+v.toLocaleString('en-US',{maximumFractionDigits:2});return'$'+v.toLocaleString('en-US',{maximumFractionDigits:5)}function compact(v){v=n(v);if(!Number.isFinite(v))return'—';const a=Math.abs(v);if(a>=1e12)return'$'+(v/1e12).toFixed(2)+'T';if(a>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(a>=1e6)return'$'+(v/1e6).toFixed(2)+'M';return'$'+Math.round(v).toLocaleString('en-US')}function change(id,v){const e=document.getElementById(id);if(!e)return;v=n(v);e.textContent=Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(2)}%`:'—';e.classList.remove('positive','negative','neutral');e.classList.add(Number.isFinite(v)?v>=0?'positive':'negative':'neutral')}
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function cp(id){const d=await get(`https://api.coinpaprika.com/v1/tickers/${id}?quotes=USD`),q=d.quotes?.USD;if(!q)throw Error('missing');return{price:n(q.price),change:n(q.percent_change_24h),cap:n(q.market_cap),volume:n(q.volume_24h),source:'CoinPaprika'}}async function cb(id){const d=await get(`https://api.exchange.coinbase.com/products/${id}/stats`),last=n(d.last),open=n(d.open),vol=n(d.volume);return{price:last,change:Number.isFinite(open)&&open?((last-open)/open)*100:NaN,cap:NaN,volume:Number.isFinite(vol)&&Number.isFinite(last)?vol*last:NaN,source:'Coinbase'}}async function bn(id){const d=await get(`https://api.binance.com/api/v3/ticker/24hr?symbol=${id}`);return{price:n(d.lastPrice),change:n(d.priceChangePercent),cap:NaN,volume:n(d.quoteVolume),source:'Binance'}}async function asset(k){const a=MARKET_ASSETS[k];try{return await Promise.any([cp(a.coinpaprika),cb(a.coinbase),bn(a.binance)])}catch(e){return{price:NaN,change:NaN,cap:NaN,volume:NaN,source:'Unavailable'}}}
function overview(k,a){const u=k==='bitcoin'?'btc':k==='ethereum'?'eth':'sol',c=n(a.change);text(`overview-${u}`,price(a.price));text(`overview-${u}-foot`,Number.isFinite(c)?`${c>=0?'+':''}${c.toFixed(2)}% over 24H · ${a.source}`:'Market feed unavailable');const b=document.getElementById(`bar-${u}`);if(b)b.style.width=Number.isFinite(c)?`${Math.min(100,Math.max(12,50+c*7))}%`:'20%'}
async function initMarketIntelligence(){if(!document.querySelector('#btc-price'))return;const s=document.querySelector('#market-status');if(s)s.textContent='Refreshing public market feeds…';const[b,e,o]=await Promise.all([asset('bitcoin'),asset('ethereum'),asset('solana')]);text('btc-price',price(b.price));change('btc-change',b.change);text('btc-cap',compact(b.cap));text('btc-volume',compact(b.volume));text('eth-price',price(e.price));change('eth-change',e.change);text('eth-cap',compact(e.cap));text('eth-volume',compact(e.volume));text('sol-price',price(o.price));change('sol-change',o.change);text('sol-volume',compact(o.volume));overview('bitcoin',b);overview('ethereum',e);overview('solana',o);let gs='';try{const g=await get('https://api.coinpaprika.com/v1/global'),tc=n(g.market_cap_usd),v=n(g.volume_24h_usd);text('total-cap',compact(tc));text('indicator-total-cap',compact(tc));text('total-volume',`24H volume: ${compact(v)}`);text('market-volume',compact(v));text('btc-dominance',Number.isFinite(Number(g.bitcoin_dominance_percentage))?Number(g.bitcoin_dominance_percentage).toFixed(2)+'%':'—');text('eth-dominance',Number.isFinite(Number(g.ethereum_dominance_percentage))?Number(g.ethereum_dominance_percentage).toFixed(2)+'%':'—');gs='CoinPaprika'}catch(x){['total-cap','indicator-total-cap','btc-dominance','eth-dominance','market-volume'].forEach(id=>text(id,'—'));text('total-volume','24H volume:  —')}const loaded=[b,e,o].filter(x=>x.source!=='Unavailable'),sources=[...new Set(loaded.map(x=>x.source))];if(s)s.textContent=loaded.length?`LIVE · ${sources.join(' / ')} · Updated ${new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}`:'Market feeds unavailable — retrying automatically';text('data-source',`Sources: ${sources.length?sources.join(' / '):'public market feeds'}${gs?' · Global: '+gs:''} · TradingView chart`);text('last-updated','Last update: '+new Date().toLocaleString('en-US',{hour:'2-digit',minute:'2-digit',month:'short',day:'numeric'}));const rel=Number.isFinite(b.price)&&Number.isFinite(e.price)&&e.price?b.price/e.price:NaN;text('btc-eth-relative',Number.isFinite(rel)?rel.toFixed(2)+' BTC/ETH':'—');const ch=[b.change,e.change,o.change].filter(Number.isFinite),avg=ch.length?ch.reduce((a,x)=>a+x,0)/ch.length:NaN;text('momentum-signal',Number.isFinite(avg)?avg>1.5?'Positive momentum':avg<-1.5?'Negative momentum':'Mixed / neutral':'Insufficient data');text('volatility-signal',ch.length>=2?(Math.max(...ch)-Math.min(...ch)>6?'Elevated':'Moderate'):'Monitoring');text('liquidity-signal',loaded.length>=2?'Multi-source liquidity available':'Limited feed coverage');text('breadth-signal',ch.length?`${ch.filter(x=>x>0).length} of ${ch.length} assets positive`:'Monitoring');text('market-regime',Number.isFinite(avg)?avg>1.5?'Risk-on bias':avg<-1.5?'Risk-off bias':'Balanced':'Analyzing')}
function initTradingViewTabs(){const f=document.getElementById('tv-chart');if(!f)return;const l=document.getElementById('chart-loading');f.addEventListener('load',()=>{if(l)l.classList.add('hidden')});document.querySelectorAll('.asset-tab[data-tv]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.asset-tab[data-tv]').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');if(l)l.classList.remove('hidden');f.src=chartUrl(b.dataset.tv);text('chart-title',b.dataset.asset==='ethereum'?'Ethereum / USD':b.dataset.asset==='solana'?'Solana / USD':'Bitcoin / USD')}))}